const { chromium } = await import(process.env.PAIR_PLAYWRIGHT_MODULE || 'playwright');
import fs from 'node:fs/promises';
await fs.mkdir('work',{recursive:true});
const base=process.env.PAIR_TEST_URL || 'http://127.0.0.1:3221';
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto(`${base}/assessment`);await page.getByText('Preparing local autosave…').waitFor({state:'hidden'});
 assert.equal(await page.locator('.dimension-disclosure[open]').count(),0);
 await page.getByRole('button',{name:'View draft profile'}).click();await page.getByRole('heading',{name:'A working draft'}).waitFor();
 await page.getByRole('link',{name:'Continue the assessment'}).click();
 await page.getByLabel('City or county name').fill('Louisville, KY');await page.getByRole('button',{name:'Find a place'}).click();
 await page.locator('.place-matches button').first().click({timeout:60000});await page.locator('.county-choice button').first().click({timeout:60000});
 await page.getByRole('heading',{name:'People and households'}).waitFor({timeout:60000});
 assert.ok((await page.locator('.place-briefing').innerText()).includes('783,022'));
 assert.equal(await page.locator('.public-evidence input[type=checkbox]').count(),0);
 await page.locator('#public-evidence').scrollIntoViewIfNeeded();await page.screenshot({path:'work/briefing-desktop.png'});
 await page.getByText('Sources, missing data and optional review',{exact:true}).click();
 await page.getByLabel('Reviewed by (only needed to attach or correct facts)').fill('Browser reviewer');
 const fact=page.locator('.briefing-record').filter({has:page.locator('summary').filter({hasText:'Resident population:'})});
 await fact.locator('summary').click();await fact.getByRole('button',{name:'Use as context'}).click();
 await fact.getByLabel('Review note',{exact:true}).fill('County context is broader than the deployment site.');
 await fact.getByLabel('Correction, if needed').fill('Use as regional context.');await fact.getByRole('button',{name:'Save correction'}).click();
 await fact.getByRole('button',{name:'Exclude this fact'}).click();
 let reviewed=await page.evaluate(()=>JSON.parse(localStorage.getItem('pair-assessment-v2')));
 // Wait for the debounced local save before testing persistence.
 await page.waitForFunction(()=>JSON.parse(localStorage.getItem('pair-assessment-v2')).automatedEvidence.reviews.length===3);
 reviewed=await page.evaluate(()=>JSON.parse(localStorage.getItem('pair-assessment-v2')));
 assert.equal(reviewed.responses['economic-development-viability'].evidence.length,0);
 await page.getByText('Sources, missing data and optional review',{exact:true}).click();
 await page.getByLabel('City or county name').fill('Oakland, CA');await page.getByRole('button',{name:'Find a place'}).click();
 await page.getByRole('button',{name:'Oakland city, CA'}).click({timeout:60000});await page.getByRole('button',{name:'Read briefing for Alameda County, CA'}).click({timeout:60000});
 await page.getByRole('heading',{name:'Alameda County',exact:true}).waitFor({timeout:90000});
 await page.setViewportSize({width:390,height:844});await page.locator('#public-evidence').scrollIntoViewIfNeeded();await page.screenshot({path:'work/briefing-mobile.png'});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
 await page.reload();await page.getByRole('heading',{name:'Alameda County',exact:true}).waitFor();
 const state=await page.evaluate(()=>JSON.parse(localStorage.getItem('pair-assessment-v2')));assert.ok(Object.values(state.responses).every(r=>r.score===null));assert.equal(state.automatedEvidence.packages.length,2);
 await page.locator('.dimension-disclosure').first().locator('summary').first().click();await page.locator('.dimension-disclosure').first().locator('label.score-option').nth(2).click();
 await page.getByRole('button',{name:'View draft profile'}).click();await page.getByText('Provisional rating — support pending').waitFor();
 assert.deepEqual(errors,[]);console.log('PASS: draft access, named city lookup, prose briefing, preserved unknowns, no automatic ratings, mobile fit, persistence, provisional rating.');
}finally{await browser.close();}
