const { chromium } = await import(process.env.PAIR_PLAYWRIGHT_MODULE || 'playwright');
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const base=process.env.PAIR_TEST_URL || 'http://127.0.0.1:3211';
await fs.mkdir('work',{recursive:true});
const browser=await chromium.launch({headless:true,channel:'chrome'});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text()+' '+m.location().url);});
try {
 await page.goto(`${base}/assessment`);
 await page.getByText('Preparing local autosave…').waitFor({state:'hidden'});
 await page.getByLabel('Case name').fill('Evidence workflow validation');
 await page.getByLabel('Assessor label').fill('Browser test reviewer');
 await page.getByLabel('Organization name').fill('Test organization');
 await page.getByLabel('Location / geography').fill('Downtown Louisville; Jefferson County context');
 await page.getByLabel('Organization type').selectOption('City / County / Public Agency');
 await page.getByLabel('Use case',{exact:false}).first().selectOption('Curb and Pickup / Drop-off Management');
 await page.getByRole('button',{name:'Find boundary',exact:true}).click();
 await page.getByRole('checkbox',{name:'I confirm this county'}).check();
 await page.getByRole('button',{name:'Build evidence profile',exact:true}).click();
 await page.getByText('8 of 8 automated indicators available.').waitFor();
 await page.getByRole('checkbox',{name:'I have checked the county boundary'}).check();
 const first=page.locator('.automated-record').filter({has:page.getByRole('heading',{name:'Resident population',exact:true})});
 await first.getByRole('button',{name:'Accept as context'}).click();
 await first.getByText('Last reviewed by Browser test reviewer').waitFor();
 let stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('pair-assessment-v2')));
 assert.equal(stored.automatedEvidence.reviews.length,1);
 assert.ok(Object.values(stored.responses).every(r=>r.score===null));
 assert.equal(stored.responses['economic-development-viability'].evidence.length,1);
 await first.getByLabel('Review note or source for correction').fill('County scope is broader than the deployment site.');
 await first.getByLabel('Correction, if needed').fill('Use only as regional context.');
 await first.getByRole('button',{name:'Save correction'}).click();
 await first.getByText('(2 review events retained.)',{exact:false}).waitFor();
 await first.getByRole('button',{name:'Reject',exact:true}).click();
 await first.getByText('(3 review events retained.)',{exact:false}).waitFor();
 const dl=page.waitForEvent('download');await page.getByRole('button',{name:'Export draft and review history'}).click();const download=await dl;await download.saveAs('work/browser-export.json');
 const exported=JSON.parse(await fs.readFile('work/browser-export.json','utf8'));
 assert.equal(exported.automatedEvidence.reviews.length,3);
 assert.equal(exported.responses['economic-development-viability'].evidence.length,0);
 await page.reload();await page.getByText('8 of 8 automated indicators available.').waitFor();
 assert.equal(await page.locator('.automated-record').count(),8);
 await page.getByLabel('County context',{exact:false}).selectOption('06075');
 await page.getByRole('button',{name:'Find boundary',exact:true}).click();
 await page.getByRole('checkbox',{name:'I confirm this county'}).check();
 await page.getByRole('button',{name:'Build evidence profile',exact:true}).click();
 await page.getByText('Source geography: San Francisco County',{exact:false}).waitFor();
 await page.locator('#public-evidence').scrollIntoViewIfNeeded();
 await page.screenshot({path:'work/evidence-desktop.png'});
 await page.getByRole('button',{name:'Refresh from public sources'}).click();
 await page.getByText('Evidence collected. Review each record before adding it to a readiness dimension.',{exact:false}).waitFor({timeout:180000});
 assert.ok((await page.evaluate(()=>JSON.parse(localStorage.getItem('pair-assessment-v2')))).automatedEvidence.packages.length>=3);
 await page.setViewportSize({width:390,height:844});
 await page.locator('#public-evidence').scrollIntoViewIfNeeded();
 await page.screenshot({path:'work/evidence-mobile.png'});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
 await page.goto(`${base}/evidence`);
 await page.getByRole('heading',{name:'PAIR indicator dictionary',exact:true}).waitFor();
 assert.equal(await page.locator('article').count(),22);
 await page.goto(`${base}/`);assert.ok((await page.locator('body').innerText()).includes('PAIR'));
 // Expected 400 for disabled live worker is a handled UI outcome, not a page error.
 const unexpected=errors.filter(e=>!e.includes('400 (Bad Request)'));
 assert.deepEqual(unexpected,[]);
 console.log(JSON.stringify({passed:true,checks:['two county boundaries','eight indicators each','accept/correct/reject','ratings remain null','export and reload preserve provenance','live refresh preserves previous snapshots','mobile no overflow','dictionary and home navigation'],consoleErrors:unexpected}));
}finally{await browser.close();}
