import { PairFrameworkVisual } from "@/components/PairFrameworkVisual";
import { SiteFooter } from "@/components/SiteFooter";
import { SiteHeader } from "@/components/SiteHeader";

export default function Home() {
  return <><SiteHeader /><main>
    <section className="hero"><div className="shell hero-grid"><div className="hero-copy"><span className="kicker"><i /> Source-available beta framework</span><h1>Readiness begins<br />before deployment.</h1><p className="hero-lede">Assess whether your place, systems, and institutions are ready for AI-enabled technologies in the physical world.</p><div className="button-row"><a className="button primary" href="/assessment">Start assessment <span aria-hidden="true">→</span></a><a className="button secondary" href="/methodology">View methodology</a></div><p className="hero-note"><span aria-hidden="true">◇</span> No account required · Your assessment stays in your browser</p></div><div className="hero-panel" aria-label="PAIR assessment overview"><div className="panel-heading"><span>PAIR readiness profile</span><span>10 dimensions</span></div><div className="pair-bars"><div className="place"><strong>P</strong><span><i style={{ width: "72%" }} /></span><em>Place</em></div><div className="architecture"><strong>A</strong><span><i style={{ width: "58%" }} /></span><em>Architecture</em></div><div className="institutions"><strong>I</strong><span><i style={{ width: "83%" }} /></span><em>Institutions</em></div><div className="returns"><strong>R</strong><span><i style={{ width: "66%" }} /></span><em>Returns</em></div></div><div className="panel-foot"><span>Evidence</span><b>→</b><span>Assessment</span><b>→</b><span>Action</span></div></div></div></section>
    <section className="intro-section"><div className="shell"><div className="section-heading split"><div><span className="eyebrow">The framework</span><h2>Four lenses. One readiness picture.</h2></div><p>The PAIR Framework evaluates readiness across Place, Architecture, Institutions, and Returns using ten evidence-based dimensions.</p></div><PairFrameworkVisual /></div></section>
    <section className="why-section"><div className="shell why-grid"><div><span className="eyebrow">Why PAIR</span><h2>Technology readiness is only part of the story.</h2></div><div className="principles"><article><span>01</span><div><h3>Place-sensitive</h3><p>Looks beyond the technology to the streets, facilities, energy systems, and public realm where deployment happens.</p></div></article><article><span>02</span><div><h3>Evidence-led</h3><p>Pairs every maturity rating with supporting notes and confidence, making assumptions visible and discussable.</p></div></article><article><span>03</span><div><h3>Action-oriented</h3><p>Turns identified gaps into practical next steps for pilots, deployment, and continuous improvement.</p></div></article></div></div></section>
    <section className="cta-section"><div className="shell cta-inner"><div><span className="eyebrow light">A clearer starting point</span><h2>Build a shared view of readiness.</h2><p>Complete the ten-dimension self-assessment, then use the results to focus expert review and next actions.</p></div><a className="button light-button" href="/assessment">Begin the assessment <span aria-hidden="true">→</span></a></div></section>
  </main><SiteFooter /></>;
}
