'use client';
import { useEffect, useRef, useState } from 'react';
import { attachPackage, indicators, parseEvidencePackage, reviewEvidence } from '@/lib/public-evidence';
import type { EvidenceReview } from '@/lib/public-evidence';
import type { AssessmentState } from '@/lib/types';
import type { PlaceMatch } from '@/lib/place-search';
import { contextBriefing } from '@/lib/context-briefing';
function observationDate(value:string){return Number.isFinite(Date.parse(value))?new Date(value).toLocaleDateString('en-US',{year:'numeric',month:'long',day:'numeric',timeZone:'UTC'}):value;}
function download(value:unknown,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
export function PublicEvidenceWorkbench({state,onChange}:{state:AssessmentState;onChange:(s:AssessmentState)=>void}) {
 const [query,setQuery]=useState(state.meta.geography || '');
 const [matches,setMatches]=useState<PlaceMatch[]>([]);
 const [counties,setCounties]=useState<{id:string;name:string;coverage:number}[]>([]);
 const [place,setPlace]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [selected,setSelected]=useState('');
 const [notes,setNotes]=useState<Record<string,string>>({});const [corrections,setCorrections]=useState<Record<string,string>>({});
 const file=useRef<HTMLInputElement>(null);const latest=useRef({state,onChange});
 // Event handlers use this render's state; asynchronous loads merge with the latest render.
 useEffect(()=>{latest.current={state,onChange};},[state,onChange]);
 const packages=state.automatedEvidence?.packages || [];const pkg=packages.find(p=>p.packageId===selected)||packages.at(-1);
 async function json(url:string){const r=await fetch(url);const b=await r.json();if(!r.ok)throw new Error(b.message || 'Lookup unavailable.');return b;}
 async function search(){setBusy(true);setCounties([]);setMatches([]);setMessage('Finding matching places…');try{const b=await json('/api/evidence/search?q='+encodeURIComponent(query));setMatches(b.matches);setMessage(b.matches.length?'Choose the place you mean.':'No matches found. Try the city or county name followed by its state.');}catch(e){setMessage(e instanceof Error?e.message:'Search unavailable.');}finally{setBusy(false);}}
 async function choose(match:PlaceMatch){setBusy(true);setPlace(`${match.name}, ${match.state}`);setMessage('Finding the county context for this place…');try{setCounties(match.kind==='county'?[{id:match.id,name:`${match.name}, ${match.state}`,coverage:100}]:(await json('/api/evidence/search?place='+match.id)).counties);setMatches([]);setMessage('Choose a county to read its briefing. City and county boundaries may differ.');}catch(e){setMessage(e instanceof Error?e.message:'County lookup unavailable.');}finally{setBusy(false);}}
 async function load(id:string){setBusy(true);setMessage('Retrieving Census and street data. This can take a minute or two…');try{
  const p=parseEvidencePackage((await json('/api/evidence/profile?geoid='+id)).profile);
  const current=latest.current.state;
  latest.current.onChange(attachPackage({...current,meta:{...current.meta,geography:current.meta.geography || place}},p));setSelected(p.packageId);setCounties([]);setMessage('Your place briefing is saved with this draft. You can continue without reviewing individual data points.');
 }catch(e){setMessage(e instanceof Error?e.message:'Profile unavailable.');}finally{setBusy(false);}}
 async function importPackage(f?:File){if(!f)return;try{if(f.size>5_000_000)throw new Error('Use a file smaller than 5 MB.');const p=parseEvidencePackage(JSON.parse(await f.text()));latest.current.onChange(attachPackage(latest.current.state,p));setSelected(p.packageId);setMessage('Briefing imported. Its sources and review history are available below.');}catch(e){setMessage(e instanceof Error?e.message:'Invalid file.');}if(file.current)file.current.value='';}
 function review(id:string,decision:EvidenceReview['decision']){if(!pkg)return;try{onChange(reviewEvidence(state,pkg,id,decision,notes[id]||'',corrections[id]||''));setMessage('Review saved. Readiness ratings are unchanged.');}catch(e){setMessage(e instanceof Error?e.message:'Review could not be saved.');}}
 return <section className="setup-card public-evidence" id="public-evidence">
  <span className="eyebrow">Place briefing · optional</span><h2>Understand the place</h2><p>Look up a US city or county for a readable overview of its people and streets, using Census and OpenStreetMap data.</p>
  <div className="place-search"><label htmlFor="place-query">City or county name<input id="place-query" value={query} disabled={busy} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();void search();}}} placeholder="Try Oakland, CA or Pittsburgh, Pennsylvania"/></label><button type="button" disabled={busy||query.trim().length<2} onClick={search}>Find a place</button></div>
  {matches.length>0&&<ul className="place-matches" aria-label="Matching places">{matches.map(m=><li key={m.kind+m.id}><button disabled={busy} onClick={()=>choose(m)}>{m.name}, {m.state}<small>{m.kind==='county'?'County':'City or community'}</small></button></li>)}</ul>}
  {counties.length>0&&<div className="county-choice"><h3>Context for {place}</h3><p>{counties.length>1?'This place spans more than one county. Choose one to explore; each briefing keeps its own boundary.':'The available briefing describes the surrounding county. It is broader than a city neighbourhood or an organization’s operating area.'}</p>{counties.map(c=><button type="button" key={c.id} disabled={busy} onClick={()=>load(c.id)}>Read briefing for {c.name}</button>)}</div>}
  <p role="status" aria-live="polite">{message}</p>
  {pkg&&<div className="place-briefing"><span className="eyebrow">County context</span><h3>{pkg.geography.name}</h3><p className="briefing-scope">This briefing covers the county boundary, not a specific facility or deployment area. Census estimates cover 2020–2024. Street observation: {observationDate(pkg.records.find(r=>r.indicatorId==='osm-street-length')?.source.observationPeriod || 'unavailable')}.</p>
   {contextBriefing(pkg).map(section=><section className="briefing-section" key={section.title}><h4>{section.title}</h4><p>{section.text}</p><p className="briefing-interpretation">{section.interpretation}</p></section>)}
   <p><strong>How to use this:</strong> Keep these facts as background while you assess the capabilities that matter to your project. You do not need to approve each fact or complete every dimension to view a draft.</p>
   <details className="briefing-details"><summary>Sources, missing data and optional review</summary><p><a href={pkg.geography.boundaryUrl} target="_blank" rel="noreferrer">View the official county boundary source</a>. Retrieved {new Date(pkg.generatedAt).toLocaleDateString()}. Missing measures remain unknown.</p>
    {pkg.warnings.map(w=><p key={w}>{w}</p>)}<label>Reviewed by (only needed to attach or correct facts)<input value={state.meta.assessorLabel} onChange={e=>onChange({...state,meta:{...state.meta,assessorLabel:e.target.value}})} placeholder="Your name or team"/></label>
    {pkg.records.map(r=>{const def=indicators.find(i=>i.id===r.indicatorId)!;const reviews=state.automatedEvidence?.reviews.filter(v=>v.packageId===pkg.packageId&&v.indicatorId===r.indicatorId)||[];const last=reviews.at(-1);return <details className="briefing-record" key={r.indicatorId}><summary>{def.title}: {r.value===null?'Not available':`${r.value.toLocaleString(undefined,{maximumFractionDigits:2})} ${r.unit}`}</summary>
     <p>{r.missingReason || r.limitations}</p><p><a href={r.source.url} target="_blank" rel="noreferrer">{r.source.name}</a> · {r.source.observationPeriod}. {r.source.license}</p>{r.marginOfError!==null&&<p>90% margin of error: ±{r.marginOfError.toLocaleString(undefined,{maximumFractionDigits:2})} {r.unit}.</p>}<p>{r.calculation}</p>
     <p>Optional: attach this fact to the relevant readiness dimensions. This does not assign a rating.</p><label>Review note<textarea value={notes[r.indicatorId]||''} onChange={e=>setNotes({...notes,[r.indicatorId]:e.target.value})}/></label><label>Correction, if needed<input value={corrections[r.indicatorId]||''} onChange={e=>setCorrections({...corrections,[r.indicatorId]:e.target.value})}/></label><div className="evidence-actions"><button disabled={r.status==='missing'} onClick={()=>review(r.indicatorId,'accepted')}>Use as context</button><button onClick={()=>review(r.indicatorId,'corrected')}>Save correction</button><button onClick={()=>review(r.indicatorId,'rejected')}>Exclude this fact</button></div>{last&&<p>{last.decision} by {last.reviewer} · {last.note} {last.correctedValue} · {reviews.length} review events retained.</p>}</details>;})}
    <a href="/evidence">Read the indicator dictionary</a>
   </details>
  </div>}
  <details className="briefing-details"><summary>Saved briefings and data export</summary>{packages.length>0&&<label>Saved briefing<select value={pkg?.packageId} onChange={e=>setSelected(e.target.value)}>{packages.map(p=><option value={p.packageId} key={p.packageId}>{p.geography.name} · {new Date(p.generatedAt).toLocaleDateString()}</option>)}</select></label>}<div className="evidence-actions"><button onClick={()=>file.current?.click()}>Import a briefing</button>{pkg&&<button onClick={()=>download(pkg,`pair-evidence-${pkg.geography.geoid}.json`)}>Export source data</button>}<button onClick={()=>download(state,'pair-assessment-draft.json')}>Export draft and review history</button></div><input ref={file} hidden type="file" accept="application/json" onChange={e=>importPackage(e.target.files?.[0])}/></details>
 </section>;
}
